# Name: Najam Rizvi
# Date: 2024/02/04
# Azure Devops CICD pipeline for Web-application Deployment

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repository: 'app-2'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build & Push to ACR
      inputs:
          containerRegistry: 'Azure Container Registry'
          repository: '$(repository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          container: 'container1'
          tags: |
            $(tag)
            latest

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.ArtifactsDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy
  dependsOn: Build 
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'Kubernetes Service Connection'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'Deployment.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
