apiVersion: app/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 2 
  selector:
    matchLabels:
      apps: myapp
  template:
    metadata:
      labels:
        apps: myapp
    spec:
      containers:
        name:
        image:
      ports:
        containerPort: 
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    apps: myapp
  ports:
    protocol: "TCP"
    port:
    targetPort:
  type: LoadBalancer
  




