apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
        - name: your-container-name  
          image: your-image-name:tag  
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appserv
spec:
  selector:
    app: myapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
